overrides:
  baseline-browser-mapping: 2.10.31
  glob: ^10.5.0
  diff@>=5.0.0 <5.2.2: ">=5.2.2"
  "@types/react": 19.2.15
  "@types/react-dom": 19.2.3

resolutionMode: highest
minimumReleaseAge: 1440
minimumReleaseAgeIgnoreMissingTime: true
allowBuilds:
  es5-ext: true
  sharp: true
  unrs-resolver: true
