import Head from 'next/head'
import Sidebar from '@/components/sidebar/Sidebar';
import { useEffect } from 'react';
import { useRouter } from 'next/router';


export default function Studies() {
    const router = useRouter()


    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='flex'>
                <p>study list</p>
            </main>
        </>
    )
}
