import Head from 'next/head'


export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='flex'>
                - CASE admin title
                - short description of the tool on this landing page

                Links to
                service status
                study management
                user management
                documentation

                - dveloped by coneno
            </main>
        </>
    )
}
