import { CardDescription } from "@/components/ui/card";
import { getReportKeys } from "@/lib/data/reports";
import ReportsToolbarClient from "./ReportsToolbarClient";
import { parseUnixSecondsToDate } from "@/lib/parse-unix-seconds-to-date";

interface ReportsToolbarProps {
    studyKey: string;
    searchParams?: {
        pid?: string;
        from?: string;
        until?: string;
        reportKey?: string;
    }
}

export default async function ReportsToolbar(props: ReportsToolbarProps) {
    const pid = props.searchParams?.pid;

    const fromDate = parseUnixSecondsToDate(props.searchParams?.from);
    const untilDate = parseUnixSecondsToDate(props.searchParams?.until);

    const reportKeysResp = await getReportKeys(
        props.studyKey,
        pid,
        fromDate,
        untilDate,
    );

    const reportKeys = reportKeysResp.reportKeys || [];

    return (
        <div className="flex flex-col gap-3">
            <CardDescription>
                Participant reports are generated by certain study rules if present in the study configuration. If they are used, you can access reports from here.
            </CardDescription>

            <ReportsToolbarClient
                reportKeys={reportKeys}
                pid={pid}
                fromDate={fromDate}
                untilDate={untilDate}
            />
        </div>
    );
}


