// TODO: Add all relevant types or remove this enum
export enum ItemComponentRole {
    Title = 'title',
    Subtitle = 'subtitle',
    HelpGroup = 'helpGroup',
    Footnote = 'footnote',
    ResponseGroup = 'responseGroup',
    Options = 'options',
    Option = 'option',
    Row = 'row',
    RowErrorHint = 'rowErrorHint',
    StartLabel = 'start',
    EndLabel = 'end',
    Matrix = 'matrix',
    HeaderRow = 'headerRow',
    ResponseRow = 'responseRow',
    DropdownGroup = 'dropDownGroup',
    TextContent = 'text',
    Cloze = 'cloze',
    TimeInput = 'timeInput',
    DateInput = 'dateInput',
    ResponsiveBipolarLikertScaleArray = 'responsiveBipolarLikertScaleArray',
    ResponsiveSingleChoiceArray = 'responsiveSingleChoiceArray',
    SingleChoiceGroup = 'singleChoiceGroup',
    MultipleChoiceGroup = 'multipleChoiceGroup',
    Markdown = 'markdown',
    Error = 'error',
    Warning = 'warning',
    Root = 'root',
}

export enum EditorMode { Properties = 'properties', ItemEditor = 'itemEditor', Simulator = 'simulator' }
